### ISSUE TITLE
Have a looping background music

### ISSUE THREAD

**Issue by Ember-Rane** [Ember-Rane/February-Moga#16]
Get a background track to loop in the background, and stop upon dying.

**Comment by DanilaFoxPro** [comment]
Added looping background music, although the code to start it is in the level blueprint. Probably should move it into a separate blueprint class that can be placed in each level.

**Comment by Ember-Rane** [comment]
Okay. Matthew will be doing the music for this if he has time. So we will
replace anything with his music if it becomes available.

**Comment by Ember-Rane** [comment]
Add in nicer music

**Comment by DanilaFoxPro** [comment]
Added in nicer music. Also added the system for random music selection, so you can just put all the music into the Music Manager options and it will handle everything.

**Comment by Ember-Rane** [comment]
Need to add last .mp3 - then it should be done
